[workspace]
authors = ["ousema-bouaneni <ousema.bouaneni@polytechnique.edu>"]
channels = ["conda-forge"]
name = "jupyter_dynare_octave"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]
setup = 'echo "addpath $CONDA_PREFIX/lib/dynare/matlab" > .octaverc'
lab = {cmd = 'jupyter lab', depends-on='setup'}

[dependencies]
jupyterlab = ">=4.4.6,<5"
xeus-octave = ">=0.3.0,<1"
dynare = {path = "./dynare"}
make = ">=4.4.1,<5"
# make needed for installation of packages by octave
